---
title: "Homework 5"
author: "Graham Montague"
date: "2025-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

```{r, echo=TRUE, eval=TRUE, results='show'}
# Question 1 : Assign to the variable n_dims a single random integer between 3 and 10.
# make this reproducible by using the set.seed() however, if you want new numbers you can comment this out
# set.seed(25) 
# randomly assign a single random integer between 3 and 10 
n_dims <- sample(3:10, 
                 size = 1)
print(n_dims)

# part a: Create a vector of consecutive integers from 1 to n_dims^2. 
# we need to create a vector of numbers 1: n_dims^2
numbers <- 1:(n_dims^2)
print(numbers)

#part b: Use the sample function to randomly reshuffle these values.
numbers <- sample(numbers)
print(numbers)

# part c: create a square matrix with these elements.
# this needs to be square so we need to use 9 X 9 matrix because
square_matrix <- matrix(numbers, 
                 nrow = n_dims, 
                 ncol = n_dims)

# part d: print out the matrix.
print(square_matrix)

# part e: find a function in r to transpose the matrix.
# I found the t() function to transpose my 9 X 9 matrix
transposed <- t(square_matrix)

# part f: print it out again and note how it has changed.
print(transposed) # it flipped flopped the columns and the rows in the matrix. For example, the value in [1,2] of 67 for the square_matrix matrix moved to [2,1] in the transposed matrix

# part g: calculate the sum and the mean of the elements in the first row and then the last row.
# For the first row of the transposed matrix
sum_first_row <- sum(transposed[1, ])
print(sum_first_row)
mean_first_row <- mean(transposed[1, ])
print(mean_first_row)

# For the last row of the transposed matrix
sum_last_row <- sum(transposed[n_dims, ])
print(sum_last_row)
mean_last_row <- mean(transposed[n_dims, ])
print(mean_last_row)

# part h: read about the eigen() function and use it on your matrix
?eigen()

eigen_matrix <- eigen(transposed)
print(eigen_matrix)

# part i: look carefully at the elements of $values and $vectors in the output. What kind of numbers are these?
eigen_values <- eigen_matrix$values
print(eigen_values)
eigen_vectors <- eigen_matrix$vectors
print(eigen_vectors)

# I have read the R help file on the output from the eigen() function. The help file states that the values and vectors may contain complex numbers. 

# part j: dig in with the typeof() function to figure out their type.
# Check the typeof() for the values of of the eigen matrix
typeof(eigen_matrix$values) 
# this returned that the values are complex

# What is the typeof() of the vectors in the eigen table?
typeof(eigen_matrix$vectors)
# This also returned a complex type

# part k: if have set your code up properly, you should be able to re-run it and create a matrix of different size because n_dims will change.

# I re ran the code and it changed the n_dims. However, if I wanted to keep the same table, I would run the set.seed() function to prevent it from changing each time and it is reproducible. 
```

## Question 2

```{r, echo=TRUE, eval=TRUE, results='show'}
# Question 2 ----------------------------------
# part a: Create a list with the following named elements: my_matrix, which is a 4 x 4 matrix filled with random uniform values
my_matrix <- matrix(runif(16), nrow = 4, ncol = 4)
print(my_matrix)

# part b: my_logical which is a 100-element vector of TRUE or FALSE values. Do this efficiently by setting up a vector of random values and then applying an inequality to it.
my_logical <- runif(100) > 0.5
print(my_logical)

# part c: my_letters, which is a 26-element vector of all the lower-case letters in random order.
my_letters <- sample(letters)
print(my_letters)

# Now I need to create a list of all of these. 
# Create the list with all three named elements
my_list <- list(
  my_matrix = my_matrix,
  my_logical = my_logical,
  my_letters = my_letters
)
str(my_list)
print(my_list)

# part d: create a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector.
my_list2 <- list(
  matrix_element = my_list$my_matrix[2,2],
  logical_element = my_list$my_logical[2],
  letter_element = my_list$my_letters[2]
)
str(my_list2)
print(my_list2)

# part e: use the typeof() function to confirm the underlying data types of each component in this list
typeof(my_list2$matrix_element) # double
typeof(my_list2$logical_element) # logical
typeof(my_list2$letter_element) # character

# part f: combine the underlying elements from the new list into a single atomic vector with the c() function.
vector <- c(my_list2$matrix_element,
            my_list2$logical_element,
            my_list2$letter_element)

# part g: what is the data type of this vector?
typeof(vector)
# it is a character
```

## Question 3

```{r, echo=TRUE, eval=TRUE, results='show'}
# Question 3 ------------------------------------
# part a: Create a data frame with the two variables (= columns) and 26 cases (= rows) below: call the first variable my_unis and fill it with 26 random uniform values from 0 to 10
# First we need to create my_unis
# part b: call the second variable my_letters and fill it with 26 capital letters in random order.
# now we need to make my_letters
my_df <- data.frame(
  my_unis = runif(26, min = 0, max = 10),
  my_letters = sample(LETTERS)
)
print(my_df)

# part c: for the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.
my_df$my_unis[sample(1:26, 4)] <- NA 

# part d: for the first variable, write a single line of R code to identify which rows have the missing values.
which(is.na(my_df$my_unis)) # columns will change if you rerun the runif() function above

# part e: re-order the entire data frame to arrange the second variable in alphabetical order
my_df <- my_df[order(my_df$my_letters), ]
print(my_df)

# part f: calculate the column mean for the first variable.
mean_variable1 <- mean(my_df$my_unis, na.rm = TRUE) 
print(mean_variable1)# 5.15755

```

End of Homework 5